apiVersion: apps/v1
kind: Deployment
metadata:
  name: cci-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cci-springboot
  template:
    metadata:
      labels:
        app: cci-springboot
    spec:
      containers:
        - name: springboot
          image: milanjohnson/cci-project:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cci-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cci-springboot